/**
 * ARV-361 (m-24): `zond generate` used to overwrite existing suite files
 * unconditionally, silently discarding agent-authored edits, while the
 * `--force` flag was a documented no-op. The auto-gen header already
 * promises "drop the header (or rename) to keep changes" — this pins that
 * contract: a suite file whose auto-gen header was removed is treated as
 * hand-edited and preserved on regenerate; `--force` overwrites it anyway;
 * files that still carry the header are always regenerated.
 */
import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdtempSync, realpathSync, rmSync, writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { readdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { generateCommand } from "../../src/cli/commands/generate.ts";
import { captureOutput } from "../_helpers/output";

const SPEC = {
  openapi: "3.0.0",
  info: { title: "tiny", version: "1.0" },
  servers: [{ url: "https://api.example.com" }],
  paths: {
    "/audiences": {
      get: { responses: { "200": { description: "ok" } } },
    },
  },
};

describe("generate: preserve hand-edited suites (ARV-361)", () => {
  let workspace: string;
  let savedCwd: string;
  let outDir: string;
  let specPath: string;

  beforeEach(() => {
    workspace = realpathSync(mkdtempSync(join(tmpdir(), "zond-gen-preserve-")));
    writeFileSync(join(workspace, "zond.config.yml"), "version: 1\n");
    savedCwd = process.cwd();
    process.chdir(workspace);
    mkdirSync(join(workspace, "apis", "demo"), { recursive: true });
    specPath = join(workspace, "apis", "demo", "spec.json");
    writeFileSync(specPath, JSON.stringify(SPEC));
    writeFileSync(join(workspace, "apis", "demo", ".env.yaml"), "base_url: https://api.example.com\n");
    outDir = join(workspace, "apis", "demo", "tests");
  });

  afterEach(() => {
    process.chdir(savedCwd);
    rmSync(workspace, { recursive: true, force: true });
  });

  async function gen(force = false): Promise<string[]> {
    const cap = captureOutput();
    await generateCommand({ specPath, output: outDir, json: true, force });
    const { out } = cap;
    cap.restore();
    try {
      return (JSON.parse(out)?.warnings as string[] | undefined) ?? [];
    } catch {
      return [];
    }
  }

  function firstSuiteFile(): string {
    const f = readdirSync(outDir).find((n) => n.endsWith(".yaml"));
    if (!f) throw new Error("no suite file generated");
    return join(outDir, f);
  }

  test("header-stripped file is preserved on regenerate; --force overwrites", async () => {
    await gen();
    const file = firstSuiteFile();

    // Agent edits: strip the auto-gen header and add a marker.
    const edited = "# my hand-authored suite\nname: edited\nsteps: []\n";
    writeFileSync(file, edited);

    const warnings = await gen(); // default: preserve
    expect(readFileSync(file, "utf-8")).toBe(edited);
    expect(warnings.some((w) => w.includes("Preserved") && w.includes("hand-edited"))).toBe(true);

    await gen(true); // --force: overwrite
    const after = readFileSync(file, "utf-8");
    expect(after).not.toBe(edited);
    expect(after.startsWith("# Auto-generated by")).toBe(true);
  });

  test("file that still carries the auto-gen header is regenerated", async () => {
    await gen();
    const file = firstSuiteFile();
    const original = readFileSync(file, "utf-8");
    expect(original.startsWith("# Auto-generated by")).toBe(true);

    // Touch it but keep the header → contract says it gets overwritten.
    writeFileSync(file, original + "\n# trailing note\n");
    const warnings = await gen();
    const after = readFileSync(file, "utf-8");
    expect(after.startsWith("# Auto-generated by")).toBe(true);
    expect(after).not.toContain("# trailing note"); // regenerated, edit gone
    expect(warnings.some((w) => w.includes("Preserved"))).toBe(false);
  });
});
