/**
 * ARV-122 (m-19, blocker-m-18): layered spec model.
 *
 * Today two artifact sources contribute to the resource map under
 * `apis/<name>/`:
 *   1. `.api-resources.yaml` — sha-tracked, regenerated by
 *      `refresh-api` from `spec.json` (upstream OpenAPI).
 *   2. `.api-resources.local.yaml` — ARV-111 user extension that
 *      survives `refresh-api` (write-only endpoints, common SaaS-style
 *      ingest, …).
 *
 * `readResourceMap` in `cli/commands/discover.ts` merges them by hand:
 * extensions win on `resource` name collision. m-18 (quicktype-derived
 * and mitmproxy-derived schema layers) will add two more sources with
 * different precedence and merge semantics — doing that ad-hoc would
 * end the way ad-hoc output-format parsing did (ARV-97 family,
 * resolved by m-19/ARV-116).
 *
 * This module is the same move for spec sources: declare each source
 * once as a `SpecLayer`, with precedence and merge policy, and feed
 * them through `composeSpec()`. The result is a `ComposedSpec` plus a
 * `ProvenanceMap` (`resource → layer.id`) that downstream code can
 * consult to explain *where* a field came from (m-18 follow-ups will
 * surface this in `doctor` / `catalog --provenance`; this task only
 * ships the internal API).
 *
 * Scope of this task: ONLY the resource-map dimension (the actual
 * `ResourceYaml` shape used by every other module). Other dimensions
 * (raw OpenAPI document, fixture manifest) keep their own loaders —
 * generalising further before there's a second consumer would be
 * premature.
 */

/** How a layer's entries combine with already-resolved entries. */
export type MergePolicy =
  /** Layer entries replace lower-precedence entries on key collision. */
  | "override"
  /** Layer entries are dropped if a lower-precedence entry already
   *  owns the key. (Useful for "default" layers that fill gaps but
   *  shouldn't shadow user input.) */
  | "preserve"
  /** Layer entries are appended even when a key already exists,
   *  producing duplicate keys. Reserved for future fixture layers;
   *  not used by the current two-layer resource composition. */
  | "append";

/** Domain a layer contributes to. Today only `resources` is wired —
 *  m-18 will likely add `fixtures` (manifest merge) and `spec`
 *  (raw OpenAPI augmentation). Listed up front so layer factories
 *  carry the tag at construction. */
export type LayerScope = "resources" | "fixtures" | "spec";

/** A single typed source of spec data. */
export interface SpecLayer<T> {
  /** Stable identifier surfaced in the provenance map (e.g.,
   *  `"upstream"`, `"extension"`, `"quicktype"`). Must be unique
   *  inside one `composeSpec` call. */
  id: string;
  /** Source path/URL for diagnostics. Optional — synthetic layers
   *  (in-memory test fixtures) can omit. */
  path?: string;
  /** Higher precedence wins on key collisions when `mergePolicy` is
   *  `"override"`. Ties: layer ordering in the input array. */
  precedence: number;
  /** Which composition this layer participates in. `composeSpec` does
   *  not currently route on scope — it expects callers to filter — but
   *  the field makes layer arrays self-describing. */
  scope: LayerScope;
  /** How this layer's entries combine with lower-precedence ones. */
  mergePolicy: MergePolicy;
  /** Load the layer's entries. Async to accommodate filesystem and
   *  network sources (an HTTP-fetched OpenAPI snapshot in the future
   *  could implement this directly). */
  load: () => Promise<T[]> | T[];
}

/** Function deriving the merge key for an entry. Pulled out so callers
 *  can compose resource lists (key = resource name) and, later, fixture
 *  lists (key = var name) with the same engine. */
export type KeyFn<T> = (entry: T) => string;

/** Output of `composeSpec`. `entries` is the merged list in stable
 *  order (lowest precedence first, with higher-precedence overrides
 *  applied in-place); `provenance` maps the merged key back to the
 *  layer id that ultimately owns it. */
export interface ComposedSpec<T> {
  entries: T[];
  provenance: Map<string, string>;
}

/**
 * Compose layers into a single entry list + provenance map.
 *
 * Order of operations:
 *   1. Layers are sorted by ascending `precedence` (low → high). A
 *      stable sort is used so ties keep input order.
 *   2. Each layer's entries are loaded in sequence (the loader is
 *      async-safe so a slow loader can't block parallel ones — but
 *      we keep ordering deterministic by awaiting in turn).
 *   3. Entries are folded into the result Map keyed by `keyFn(entry)`:
 *        - `mergePolicy === "override"` → replace; provenance updates.
 *        - `mergePolicy === "preserve"` → only set if the key is new.
 *        - `mergePolicy === "append"`   → key suffixed with `#<n>` to
 *          avoid collision; provenance still recorded.
 *
 * The result preserves insertion order of the underlying Map, which
 * is the natural "lowest-precedence-first" view: callers that need a
 * different ordering re-sort downstream.
 */
export async function composeSpec<T>(
  layers: SpecLayer<T>[],
  keyFn: KeyFn<T>,
): Promise<ComposedSpec<T>> {
  const ordered = [...layers].sort((a, b) => a.precedence - b.precedence);

  const seenIds = new Set<string>();
  for (const l of ordered) {
    if (seenIds.has(l.id)) {
      throw new Error(`composeSpec: duplicate layer id "${l.id}"`);
    }
    seenIds.add(l.id);
  }

  const merged = new Map<string, T>();
  const provenance = new Map<string, string>();
  let appendCounter = 0;

  for (const layer of ordered) {
    const entries = await layer.load();
    for (const entry of entries) {
      const key = keyFn(entry);
      switch (layer.mergePolicy) {
        case "override":
          merged.set(key, entry);
          provenance.set(key, layer.id);
          break;
        case "preserve":
          if (!merged.has(key)) {
            merged.set(key, entry);
            provenance.set(key, layer.id);
          }
          break;
        case "append": {
          const tagged = `${key}#${appendCounter++}`;
          merged.set(tagged, entry);
          provenance.set(tagged, layer.id);
          break;
        }
      }
    }
  }

  return { entries: Array.from(merged.values()), provenance };
}
