import type { EndpointInfo, SecuritySchemeInfo } from "./types.ts";
import { compressSchema, formatParam, isAnySchema } from "./schema-utils.ts";

export interface CatalogEndpoint {
  method: string;
  path: string;
  summary?: string;
  tags: string[];
  deprecated?: boolean;
  parameters?: string[];
  requestBody?: string;
  responses: Array<{
    status: number;
    schema?: string;
  }>;
}

export interface ApiCatalog {
  generatedAt: string;
  specSource: string;
  specHash: string;
  apiName?: string;
  apiVersion?: string;
  baseUrl?: string;
  auth: string[];
  endpointCount: number;
  endpoints: CatalogEndpoint[];
}

export interface BuildCatalogParams {
  endpoints: EndpointInfo[];
  securitySchemes: SecuritySchemeInfo[];
  specSource: string;
  specHash: string;
  apiName?: string;
  apiVersion?: string;
  baseUrl?: string;
}

function formatSecurityScheme(s: SecuritySchemeInfo): string {
  let desc = `${s.name}: ${s.type}`;
  if (s.scheme) desc += `/${s.scheme}`;
  if (s.bearerFormat) desc += ` (${s.bearerFormat})`;
  if (s.in && s.apiKeyName) desc += ` (${s.apiKeyName} in ${s.in})`;
  return desc;
}

function formatParamWithLocation(p: import("openapi-types").OpenAPIV3.ParameterObject): string {
  const base = formatParam(p);
  // Insert location before (req) or at the end
  const reqSuffix = " (req)";
  if (base.endsWith(reqSuffix)) {
    return `${base.slice(0, -reqSuffix.length)} (${p.in}, req)`;
  }
  return `${base} (${p.in})`;
}

function buildCatalogEndpoint(ep: EndpointInfo): CatalogEndpoint {
  const result: CatalogEndpoint = {
    method: ep.method.toUpperCase(),
    path: ep.path,
    tags: ep.tags,
    responses: [],
  };

  if (ep.summary) result.summary = ep.summary;
  if (ep.deprecated) result.deprecated = true;

  if (ep.parameters.length > 0) {
    result.parameters = ep.parameters.map(formatParamWithLocation);
  }

  if (ep.requestBodySchema) {
    result.requestBody = isAnySchema(ep.requestBodySchema)
      ? "any"
      : compressSchema(ep.requestBodySchema);
  }

  for (const resp of ep.responses) {
    const entry: { status: number; schema?: string } = { status: resp.statusCode };
    if (resp.schema && !isAnySchema(resp.schema)) {
      entry.schema = compressSchema(resp.schema);
    }
    result.responses.push(entry);
  }

  return result;
}

export function buildCatalog(params: BuildCatalogParams): ApiCatalog {
  return {
    generatedAt: new Date().toISOString(),
    specSource: params.specSource,
    specHash: params.specHash,
    ...(params.apiName ? { apiName: params.apiName } : {}),
    ...(params.apiVersion ? { apiVersion: params.apiVersion } : {}),
    ...(params.baseUrl ? { baseUrl: params.baseUrl } : {}),
    auth: params.securitySchemes.map(formatSecurityScheme),
    endpointCount: params.endpoints.length,
    endpoints: params.endpoints.map(buildCatalogEndpoint),
  };
}

// --- YAML serialization ---

function yamlEscape(value: string): string {
  if (/[:{}\[\],&*#?|<>=!%@`"']/.test(value) || value.includes("\n")) {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return value;
}

function yamlScalar(value: unknown): string {
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  return yamlEscape(String(value));
}

export function serializeCatalog(catalog: ApiCatalog): string {
  const lines: string[] = [];
  lines.push("# Auto-generated by zond. Regenerate with: zond catalog <spec>");
  lines.push(`generatedAt: ${yamlScalar(catalog.generatedAt)}`);
  lines.push(`specSource: ${yamlScalar(catalog.specSource)}`);
  lines.push(`specHash: ${yamlScalar(catalog.specHash)}`);
  if (catalog.apiName) lines.push(`apiName: ${yamlScalar(catalog.apiName)}`);
  if (catalog.apiVersion) lines.push(`apiVersion: ${yamlScalar(catalog.apiVersion)}`);
  if (catalog.baseUrl) lines.push(`baseUrl: ${yamlScalar(catalog.baseUrl)}`);
  lines.push(`endpointCount: ${catalog.endpointCount}`);

  // Auth
  if (catalog.auth.length > 0) {
    lines.push("auth:");
    for (const a of catalog.auth) {
      lines.push(`  - ${yamlScalar(a)}`);
    }
  } else {
    lines.push("auth: []");
  }

  // Endpoints
  if (catalog.endpoints.length === 0) {
    lines.push("endpoints: []");
    return lines.join("\n") + "\n";
  }
  lines.push("endpoints:");
  for (const ep of catalog.endpoints) {
    lines.push(`  - method: ${ep.method}`);
    lines.push(`    path: ${yamlScalar(ep.path)}`);
    if (ep.summary) lines.push(`    summary: ${yamlScalar(ep.summary)}`);
    if (ep.tags.length > 0) {
      lines.push(`    tags: [${ep.tags.map(yamlScalar).join(", ")}]`);
    }
    if (ep.deprecated) lines.push(`    deprecated: true`);

    if (ep.parameters && ep.parameters.length > 0) {
      lines.push(`    parameters:`);
      for (const p of ep.parameters) {
        lines.push(`      - ${yamlScalar(p)}`);
      }
    }

    if (ep.requestBody) {
      lines.push(`    requestBody: ${yamlScalar(ep.requestBody)}`);
    }

    if (ep.responses.length > 0) {
      lines.push(`    responses:`);
      for (const r of ep.responses) {
        if (r.schema) {
          lines.push(`      - status: ${r.status}`);
          lines.push(`        schema: ${yamlScalar(r.schema)}`);
        } else {
          lines.push(`      - status: ${r.status}`);
        }
      }
    }
  }

  return lines.join("\n") + "\n";
}
