/**
 * Shell completion script generator.
 *
 * Builds a static completion script from a commander program tree. No external
 * completion library — bash/zsh/fish templates are inlined.
 *
 * Install:
 *   bash:  zond completions bash > ~/.local/share/bash-completion/completions/zond
 *   zsh:   zond completions zsh  > ~/.zsh/completions/_zond  (then `compinit`)
 *   fish:  zond completions fish > ~/.config/fish/completions/zond.fish
 */

import type { Command } from "commander";

export const COMPLETION_SHELLS = ["bash", "zsh", "fish"] as const;
export type CompletionShell = (typeof COMPLETION_SHELLS)[number];

export interface CompletionsOptions {
  shell: CompletionShell;
  program: Command;
}

interface CommandSpec {
  name: string;
  description: string;
  options: string[]; // long flags only, e.g. ["--tag", "--safe"]
  subcommands: CommandSpec[];
}

function extractSpec(cmd: Command): CommandSpec {
  // Option's internal shape exposes `long`; commander v14 keeps this stable.
  const rawOpts = cmd.options as unknown as Array<{ long?: string }>;
  const opts: string[] = rawOpts
    .map((o) => o.long)
    .filter((s): s is string => typeof s === "string");

  return {
    name: cmd.name(),
    description: cmd.description(),
    options: opts,
    // Drop commander's auto `help` subcommand to keep templates lean.
    subcommands: cmd.commands
      .filter((c) => c.name() !== "help")
      .map(extractSpec),
  };
}

// ── bash ──

function renderBash(root: CommandSpec): string {
  const topLevel = root.subcommands.map((s) => s.name).join(" ");

  const perCmd = root.subcommands
    .map((sub) => {
      const flags = sub.options.join(" ");
      const subs = sub.subcommands.map((s) => s.name).join(" ");
      return `        ${sub.name})
            COMPREPLY=( $(compgen -W "${[flags, subs].filter(Boolean).join(" ")}" -- "$cur") )
            return 0
            ;;`;
    })
    .join("\n");

  return `# bash completion for zond — generated by 'zond completions bash'
_zond_completion() {
    local cur prev
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"

    if [ "\$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "${topLevel} --help --version" -- "$cur") )
        return 0
    fi

    case "\${COMP_WORDS[1]}" in
${perCmd}
    esac
}
complete -F _zond_completion zond
`;
}

// ── zsh ──

function renderZsh(root: CommandSpec): string {
  const cmdLines = root.subcommands
    .map((s) => `        '${s.name}:${s.description.replace(/'/g, "'\\''")}'`)
    .join(" \\\n");

  const perCmd = root.subcommands
    .map((sub) => {
      const flagSpecs = sub.options
        .map((f) => `                    '${f}[${f.slice(2)}]'`)
        .join(" \\\n");
      const subCmds = sub.subcommands.length > 0
        ? `\n                _values 'subcommand' \\\n` +
          sub.subcommands.map((s) => `                    '${s.name}[${s.description.replace(/'/g, "'\\''")}]'`).join(" \\\n")
        : "";
      return `        ${sub.name})
            _arguments \\
${flagSpecs || "                    ':path:_files'"}${subCmds}
            ;;`;
    })
    .join("\n");

  return `#compdef zond
# zsh completion for zond — generated by 'zond completions zsh'

_zond() {
    local context state state_descr line
    local -A opt_args

    _arguments -C \\
        '1: :->command' \\
        '*::arg:->args'

    case $state in
        command)
            _values 'zond command' \\
${cmdLines}
            ;;
        args)
            case $line[1] in
${perCmd}
            esac
            ;;
    esac
}

_zond "$@"
`;
}

// ── fish ──

function renderFish(root: CommandSpec): string {
  const lines: string[] = [
    "# fish completion for zond — generated by 'zond completions fish'",
  ];

  for (const sub of root.subcommands) {
    const desc = sub.description.replace(/'/g, "\\'");
    lines.push(`complete -c zond -n '__fish_use_subcommand' -a '${sub.name}' -d '${desc}'`);
  }
  lines.push(`complete -c zond -n '__fish_use_subcommand' -l help -d 'Show help'`);
  lines.push(`complete -c zond -n '__fish_use_subcommand' -l version -d 'Show version'`);

  for (const sub of root.subcommands) {
    const condition = `__fish_seen_subcommand_from ${sub.name}`;
    for (const opt of sub.options) {
      lines.push(`complete -c zond -n '${condition}' -l ${opt.slice(2)}`);
    }
    for (const nested of sub.subcommands) {
      const desc = nested.description.replace(/'/g, "\\'");
      lines.push(`complete -c zond -n '${condition}' -a '${nested.name}' -d '${desc}'`);
    }
  }

  return lines.join("\n") + "\n";
}

// ── Public entry ──

export function completionsCommand(options: CompletionsOptions): number {
  const spec = extractSpec(options.program);

  let script: string;
  switch (options.shell) {
    case "bash": script = renderBash(spec); break;
    case "zsh":  script = renderZsh(spec);  break;
    case "fish": script = renderFish(spec); break;
  }

  process.stdout.write(script);
  return 0;
}
